### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: capacity < 0: -1946156200

### ISSUE THREAD

**Issue by weituotian** [sakebook/KuromojiSample#1]
```
Caused by: java.lang.IllegalArgumentException: capacity < 0: -1946156200
at java.nio.ByteBuffer.allocate(ByteBuffer.java:54)
                                                                              at com.atilika.kuromoji.io.IntegerArrayIO.readArray(IntegerArrayIO.java:38)
                                                                              at com.atilika.kuromoji.buffer.WordIdMap.<init>(WordIdMap.java:35)
                                                                              at com.atilika.kuromoji.dict.TokenInfoDictionary.setup(TokenInfoDictionary.java:168)
                                                                              at com.atilika.kuromoji.dict.TokenInfoDictionary.newInstance(TokenInfoDictionary.java:160)
                                                                              at com.atilika.kuromoji.ipadic.Tokenizer$Builder.loadDictionaries(Tokenizer.java:219)
                                                                              at com.atilika.kuromoji.TokenizerBase.configure(TokenizerBase.java:77) 
                                                                              at com.atilika.kuromoji.ipadic.Tokenizer.<init>(Tokenizer.java:74) 
                                                                              at com.atilika.kuromoji.ipadic.Tokenizer.<init>(Tokenizer.java:65) 
                                                                              at com.weituotian.fiftytone.fragment.WordsFragment.init(WordsFragment.java:79) 
                                                                              at com.weituotian.fiftytone.fragment.WordsFragment.onViewCreated(WordsFragment.java:70) 
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314) 
                                                                              at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528) 
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595) 
                                                                              at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758) 
                                                                              at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363) 
                                                                              at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149) 
                                                                              at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103) 
                                                                              at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013) 
                                                                              at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710) 
                                                                              at android.os.Handler.handleCallback(Handler.java:739) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                              at android.os.Looper.loop(Looper.java:135) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5290) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706) 
```

**Comment by sakebook** [comment]
I can not reproduce. Please retry build on master. Updated environment.
